# Generated by Django 5.0.6 on 2024-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_pedido_estado_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
